// uxpin/src/c4-button/c4-button.jsx
import React from "react";
import { C4Button as _C4Button } from "../../../react-components/dist";
import PropTypes, { oneOf } from "prop-types";
import { sizeToUtility } from "../utilities";

function C4Button(props) {
  return (
    <_C4Button {...props} className={sizeToUtility(props.size)}>
      {props.children}
    </_C4Button>
  );
}

C4Button.propTypes = {
  children: PropTypes.string,
  disabled: PropTypes.bool,
  buttonClass: PropTypes.oneOf(['secondary', 'tertiary']),
  tag: PropTypes.oneOf(["button", "a"]),
  type: PropTypes.oneOf(["submit", "reset", "button"]),
  href: PropTypes.string,
  size: PropTypes.number,
};

export { C4Button as default };

// stencil-components/src/components/c4-button/c4-button.tsx
import { Component, Prop, h } from "@stencil/core";


@Component({
  tag: "c4-button",
  styleUrl: "c4-button.css"
})
export class C4Button {
  @Prop() disabled: boolean = false;
  @Prop() type: string = "button";
  @Prop() tag: string = "button";
  @Prop() href: string = "#";
  @Prop() buttonClass?: 'secondary' | 'tertiary' | 'right' | 'left';

  private getClass(): string {
    let className = "c4-button";

    if (this.buttonClass) {
      className += ` c4-button--${this.buttonClass}`;
    }

    return className;
  }

  render() {
    if (this.tag === "a") {
      return (
        <a href={this.href} class={this.getClass()}>
          <slot />
        </a>
      );
    } else {
      return (
        <this.tag
          disabled={this.disabled}
          class={this.getClass()}
          type={this.type}
        >
          <slot />
        </this.tag>
      );
    }
  }
}
