// my-react-app/src/App.js
import React from "react";
import "./App.css";
import "../../stencil-components/src/css/base.css";
import { C4Button, C4Heading, C4Container } from "../../react-components";

import { SwatchWrapper } from "./components/swatch-wrapper";

function App() {
  return (
    <div className="App">
      <C4Container contentClass="prose">
        <C4Heading>A React App Consuming Stencil Components</C4Heading>

        <p>
          This button is a web component I created using stencil-js and exported
          for use in a React app.
        </p>

        <C4Button>Hello world!</C4Button>
      </C4Container>
      <C4Container contentClass="prose" containerClass="dark">
        <C4Heading tag="h2">A Themed Container</C4Heading>

        <p>
          This container is using the <code>dark</code> theme modifier.
        </p>

        <C4Button>Hello world!</C4Button>
      </C4Container>

      <SwatchWrapper
        radioName="colors"
        colorsData={[
          { hex: "#215cca", name: "Cloud Blue", id: "123" },
          { hex: "#158466", name: "PNW Green", id: "124" },
          { hex: "#d9118f", name: "PWA Pink", id: "125" },
          { hex: "#f27041", name: "Orange", id: "126" },
          { hex: "#485968", name: "Grey", id: "127" },
        ]}
      ></SwatchWrapper>
    </div>
  );
}

export default App;

// vue-app/src/App.vue
<template>
  <C4Container>
    <h1>Vue App</h1>

    <p>
      This Vue app is using a Vue wrapper around our
      <code>c4-color-swatches</code>
      custom element. This wrapper allows us to use Vue style event and data
      binding.
    </p>

    <h2>Color Swatches</h2>

    <p>
      Selected Color:
      <em>
        {{ selectedColor }}
      </em>
    </p>

    <C4ColorSwatches
      radio-name='colors'
      :colors='colors'
      @colorChanged='changeColor'
    ></C4ColorSwatches>
  </C4Container>
</template>

<script>
import C4Container from './components/C4Container';
import C4ColorSwatches from './components/C4ColorSwatches';

export default {
  name: 'App',
  components: {
    C4ColorSwatches,
    C4Container,
  },
  data() {
    return {
      selectedColor: 'Cloud Blue',
      colors: [
        { hex: '#215cca', name: 'Cloud Blue', id: '123' },
        { hex: '#158466', name: 'PNW Green', id: '124' },
        { hex: '#d9118f', name: 'PWA Pink', id: '125' },
        { hex: '#f27041', name: 'Cloud Fourange', id: '126' },
        { hex: '#485968', name: 'Grey', id: '127' },
      ],
    };
  },
  methods: {
    changeColor({ name }) {
      this.selectedColor = name;
    },
  },
};
</script>
